name 'netmanagers-thin'
version '0.0.1'

author 'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com'
source 'https://github.com/netmanagers/puppet-thin'
summary 'Puppet module for thin'
description 'This module installs and manages thin. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
